name: .NET Framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.5.x
    - name: Restore dependencies
      run: dotnet restore ./SfdcConnect.sln
    - name: Build
      run: dotnet build SfdcConnect/SfdcConnect.Framework.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
